### ISSUE TITLE
Transformers integration and hosting the model on Huggingface hub 🤗

### ISSUE THREAD

**Issue by patil-suraj** [coteries/cedille-ai#1]
Hey @MasterScrat !

Great work and the demo UI is so beautiful 😍 !

Would be really cool to have this model on the [huggingface hub](https://huggingface.co)! I see you currently save your model checkpoints through google storage. Would you be interested in sharing the model in the [Hugging Face Hub](http://hf.co/models)? 

This integration would allow anyone from the community to easily download and use the model from the Hub.
We can help you set up a `cedille-ai` organization. You can create an org [here.](https://huggingface.co/organizations/new)

The GPT-J architecture is already available in `Transformers` in `PyTorch`.  And this [script ](https://github.com/kingoflolz/mesh-transformer-jax/blob/master/to_hf_weights.py) can be used to convert the jax checkpoint to pt. 

Once you have the weights in PT it should be fairly easy to push the model on the hub.

```python3
from transformers import GPTJForCausalLM

model = GPTJForCausalLM.from_pretrained("path_to_converted_ckpt")
model.push_to_hub("boris-6b", organization="cedille-ai")
```

then users can simply use it using

```python3
model = GPTJForCausalLM.from_pretrained("cedille-ai/boris-6b")
```

Manually creating the repos and adding new models should also be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions. Thank you!

(cc @LysandreJik)

**Comment by MasterScrat** [comment]
Cedille is now on HuggingFace! 🤗 🚀

https://huggingface.co/Cedille/fr-boris
